---
title: "R Notebook"
output:
  html_document:
    df_print: paged
---

Read in ALOS and Landsat extracted values

```{r}
setwd("/Users/apple/Dropbox/PKNP/ALOS_Landsat")

al=read.csv("alosland.csv")

head(al)

```

Kruskal Wallis Tests- Landsat

```{r}
## Landsat
library(pgirmess)
kruskal.test(split_landsatb_B1 ~ class, data = al) 
kruskalmc(al$split_landsatb_B1, al$class)

kruskal.test(split_landsatb_B2 ~ class, data = al) 
kruskalmc(al$split_landsatb_B2, al$class)

kruskal.test(split_landsatb_B3 ~ class, data = al)
kruskalmc(al$split_landsatb_B3, al$class)

kruskal.test(split_landsatb_B4 ~ class, data = al) 
kruskalmc(al$split_landsatb_B4, al$class)

kruskal.test(split_landsatb_B5 ~ class, data = al) 
kruskalmc(al$split_landsatb_B5, al$class)

kruskal.test(split_landsatb_B6 ~ class, data = al) 
kruskalmc(al$split_landsatb_B6, al$class)

kruskal.test(split_landsatb_B7 ~ class, data = al) 
kruskalmc(al$split_landsatb_B7, al$class)

kruskal.test(split_landsatb_B8 ~ class, data = al) 
kruskalmc(al$split_landsatb_B8, al$class)

```

Set Factor

```{r}
al$lulc <- factor(al$class,labels = c("Cashew", "Bare Earth", "Regenerating_Less10", "Regenerating_More10", "Selective Logging","Intact","Degraded"))

```

Kruskal Wallis Tests- ALOS

```{r}
kruskal.test(HH_pknp ~ class, data = al) 


kruskal.test(HV_pknp ~ class, data = al) 
kruskalmc(al$HV_pknp, al$class)

kruskal.test(RFDI2016 ~ class, data = al) 
kruskalmc(al$RFDI2016, al$class)

kruskal.test(Ratio2016 ~ class, data = al) 
kruskalmc(al$Ratio2016, al$class)

```

Boxplots
#https://bbolker.github.io/R-ecology-lesson/04-visualization-ggplot2.html

```{r}
library(ggplot2)
ggplot(al, aes(x = lulc, y = Ratio2016, fill=lulc)) +
        geom_boxplot()+theme(axis.text.x  = element_text(angle=90, vjust=0.5, size=8))

ggplot(al, aes(x = lulc, y = RFDI2016, fill=lulc)) +
        geom_boxplot()+theme(axis.text.x  = element_text(angle=90, vjust=0.5, size=8))

```

